### ISSUE TITLE
 Enable/disable connected standby?

### ISSUE THREAD

**Issue by kohanyirobert** [MotorBottle/S3-Sleep-on-Rog-G14-15-2021-2022-using-OpenCore#3]
Sorry for littering your issue list, but I wanted to ask whether using the method you explain in this repo would be possible to enable connected standby in S0? I have a GA402RK (2022 G14 model I believe). I don't like S0 too much, but I've read enabling S3 can cause weird issues. My only real beef is not being able to use Wake-on-LAN because of S0 disconnected mode. Thanks for info.

**Comment by MotorBottle** [comment]
Search G-helper on GitHub and I think that app is a perfect substitute to armory center. And it seems to have a sleep-related option

**Comment by kohanyirobert** [comment]
I'm using G-Helper, but it's not design for this. What I aim to achieve is to enable "Connectivity in standby" (see my `powercfg /a` output). S3 could work, I'll will try it sometime, but I'm content with S0 (since my laptop is mostly on charger), but not being able to do Wake-on-LAN is a pain in the ass.

```
The following sleep states are available on this system:
    Standby (S0 Low Power Idle) Network Disconnected
    Hibernate
    Fast Startup

The following sleep states are not available on this system:
    Standby (S1)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Standby (S2)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Standby (S3)
        The system firmware does not support this standby state.
        This standby state is disabled when S0 low power idle is supported.

    Hybrid Sleep
        Standby (S3) is not available.
        The hypervisor does not support this standby state.

    Standby (S0 Low Power Idle) Network Connected
        Connectivity in standby is not supported.
```

**Comment by MotorBottle** [comment]
Understood but I’m not expert on this, so unluckily couldn’t help on that.

But If you specifically aim at waking the laptop through net, you might wanna try esp32s2/esp32s3/raspberry pi. These boards are capable of acting as usb devices (let’s say a keyboard), and they could keep connected to work and listening to commands with very low power. I myself had used esp32s3 which usually cost $3-5 to emulate MNK devices. So it could be an option, even not as good as WOL.

**Comment by kohanyirobert** [comment]
Thanks for the info. Great idea, I tried a wireless mouse with a USB dongle
to wake the computer when I'm at home but the walls are too thick :D Great
idea with the ESP, I'll look into it. Thanks!

**Comment by kohanyirobert** [comment]
If anyone interested I solved this problem using a LILYGO T-Dongle-S3 ESP32S3 dev board. Works like a charm!

**Comment by MotorBottle** [comment]
It is nice to hear that
